/**
 * Integrantes:
 * CERVANTES CRUZ EDGAR
 * GARCIA TRINIDAD EMIR ESTEBAN
 * LOPEZ DEL CASTILLO DANIEL ISAY
 * PEREZ MENDIETA ALDO
*/

package creargrafo;

import grafo.Graph;
import clases.Estacion;
import clases.Via;

public class CrearGrafo {
    
    /**
     * Método que se llama cada vez que se inicia el programa, crea un grafo de
     * {@code Estacion} que llena con datos del Sistema de Transporte Colectivo
     * Metro basado en {@link https://metro.cdmx.gob.mx/longitud-de-estacion}.
     * 
     * @return Grafo con todas las estaciones e interestaciones del metro de CDMX
     */
    public static Graph<Estacion> crearGrafo() {
        
        Graph<Estacion> g = new Graph<>(false);
        
        g.addNode(new Estacion("Observatorio", 105, 560));
        g.addNode(new Estacion("Tacubaya", 133, 532));
        g.addNode(new Estacion("Juanacatlán", 143, 496));
        g.addNode(new Estacion("Chapultepec", 163, 476));
        g.addNode(new Estacion("Sevilla", 177, 463));
        g.addNode(new Estacion("Insurgentes", 195, 444));
        g.addNode(new Estacion("Cuauhtémoc", 218, 428));
        g.addNode(new Estacion("Balderas", 245, 428));
        g.addNode(new Estacion("Salto del Agua", 266, 427));
        g.addNode(new Estacion("Isabel la Católica", 282, 428));
        g.addNode(new Estacion("Pino Suárez", 297, 428));
        g.addNode(new Estacion("Merced", 322, 424));
        g.addNode(new Estacion("Candelaria", 339, 406));
        g.addNode(new Estacion("San Lázaro", 356, 402));
        g.addNode(new Estacion("Moctezuma", 377, 405));
        g.addNode(new Estacion("Balbuena", 398, 422));
        g.addNode(new Estacion("Boulevard Puerto Aéreo", 414, 437));
        g.addNode(new Estacion("Gómez Farías", 430, 452));
        g.addNode(new Estacion("Zaragoza", 463, 456));
        g.addNode(new Estacion("Pantitlán", 493, 436));
        g.addNode(new Estacion("Cuatro Caminos", 19, 342));
        g.addNode(new Estacion("Panteones", 51, 342));
        g.addNode(new Estacion("Tacuba", 94, 341));
        g.addNode(new Estacion("Cuitláhuac", 130, 342));
        g.addNode(new Estacion("Popotla", 151, 352));
        g.addNode(new Estacion("Colegio Militar", 164, 367));
        g.addNode(new Estacion("Normal", 179, 383));
        g.addNode(new Estacion("San Cosme", 199, 396));
        g.addNode(new Estacion("Revolución", 219, 395));
        g.addNode(new Estacion("Hidalgo", 244, 396));
        g.addNode(new Estacion("Bellas Artes", 267, 396));
        g.addNode(new Estacion("Allende", 284, 396));
        g.addNode(new Estacion("Zócalo", 295, 406));
        g.addNode(new Estacion("San Antonio Abad", 295, 462));
        g.addNode(new Estacion("Chabacano", 295, 492));
        g.addNode(new Estacion("Viaducto", 294, 514));
        g.addNode(new Estacion("Xola", 295, 539));
        g.addNode(new Estacion("Villa de Cortés", 295, 562));
        g.addNode(new Estacion("Nativitas", 295, 585));
        g.addNode(new Estacion("Portales", 294, 624));
        g.addNode(new Estacion("Ermita", 295, 652));
        g.addNode(new Estacion("General Anaya", 295, 682));
        g.addNode(new Estacion("Tasqueña", 308, 708));
        g.addNode(new Estacion("Indios Verdes", 302, 184));
        g.addNode(new Estacion("Deportivo 18 de Marzo", 293, 227));
        g.addNode(new Estacion("Potrero", 278, 242));
        g.addNode(new Estacion("La Raza", 261, 259));
        g.addNode(new Estacion("Tlatelolco", 245, 332));
        g.addNode(new Estacion("Guerrero", 244, 366));
        g.addNode(new Estacion("Juárez", 244, 411));
        g.addNode(new Estacion("Niños Héroes", 243, 460));
        g.addNode(new Estacion("Hospital General", 235, 482));
        g.addNode(new Estacion("Centro Médico", 236, 501));
        g.addNode(new Estacion("Etiopía/Plaza de la Transparencia", 235, 544));
        g.addNode(new Estacion("Eugenia", 235, 576));
        g.addNode(new Estacion("División del Norte", 235, 599));
        g.addNode(new Estacion("Zapata", 219, 628));
        g.addNode(new Estacion("Coyoacán", 190, 658));
        g.addNode(new Estacion("Viveros/Derechos Humanos", 183, 693));
        g.addNode(new Estacion("Miguel Ángel de Quevedo", 183, 719));
        g.addNode(new Estacion("Copilco", 194, 754));
        g.addNode(new Estacion("Universidad", 211, 791));
        g.addNode(new Estacion("Martín Carrera", 357, 216));
        g.addNode(new Estacion("Talismán", 359, 251));
        g.addNode(new Estacion("Bondojito", 348, 289));
        g.addNode(new Estacion("Consulado", 339, 320));
        g.addNode(new Estacion("Canal del Norte", 340, 341));
        g.addNode(new Estacion("Morelos", 339, 380));
        g.addNode(new Estacion("Fray Servando", 339, 436));
        g.addNode(new Estacion("Jamaica", 339, 470));
        g.addNode(new Estacion("Santa Anita", 340, 500));
        g.addNode(new Estacion("Politécnico", 191, 189));
        g.addNode(new Estacion("Instituto del Petróleo", 221, 219));
        g.addNode(new Estacion("Autobuses del Norte", 245, 244));
        g.addNode(new Estacion("Misterios", 296, 295));
        g.addNode(new Estacion("Valle Gómez", 318, 316));
        g.addNode(new Estacion("Eduardo Molina", 378, 320));
        g.addNode(new Estacion("Aragón", 407, 321));
        g.addNode(new Estacion("Oceanía", 432, 344));
        g.addNode(new Estacion("Terminal Aérea", 442, 382));
        g.addNode(new Estacion("Hangares", 452, 414));
        g.addNode(new Estacion("El Rosario", 48, 187));
        g.addNode(new Estacion("Tezozómoc", 74, 217));
        g.addNode(new Estacion("Azcapotzalco", 97, 232));
        g.addNode(new Estacion("Ferrería", 138, 232));
        g.addNode(new Estacion("Norte 45", 175, 232));
        g.addNode(new Estacion("Vallejo", 195, 233));
        g.addNode(new Estacion("Lindavista", 260, 219));
        g.addNode(new Estacion("La Villa-Basílica", 322, 228));
        g.addNode(new Estacion("Aquiles Serdán", 63, 232));
        g.addNode(new Estacion("Camarones", 95, 268));
        g.addNode(new Estacion("Refinería", 95, 300));
        g.addNode(new Estacion("San Joaquín", 95, 387));
        g.addNode(new Estacion("Polanco", 95, 427));
        g.addNode(new Estacion("Auditorio", 95, 454));
        g.addNode(new Estacion("Constituyentes", 109, 508));
        g.addNode(new Estacion("San Pedro de los Pinos", 141, 568));
        g.addNode(new Estacion("San Antonio", 141, 592));
        g.addNode(new Estacion("Mixcoac", 140, 624));
        g.addNode(new Estacion("Barranca del Muerto", 140, 668));
        g.addNode(new Estacion("Garibaldi", 267, 368));
        g.addNode(new Estacion("San Juan de Letrán", 267, 411));
        g.addNode(new Estacion("Doctores", 267, 448));
        g.addNode(new Estacion("Obrera", 279, 472));
        g.addNode(new Estacion("La Viga", 321, 499));
        g.addNode(new Estacion("Coyuya", 367, 516));
        g.addNode(new Estacion("Iztacalco", 391, 540));
        g.addNode(new Estacion("Apatlaco", 400, 573));
        g.addNode(new Estacion("Aculco", 399, 597));
        g.addNode(new Estacion("Escuadrón 201", 400, 622));
        g.addNode(new Estacion("Atlalilco", 420, 651));
        g.addNode(new Estacion("Iztapalapa", 466, 649));
        g.addNode(new Estacion("Cerro de la Estrella", 491, 649));
        g.addNode(new Estacion("U.A.M. I", 530, 656));
        g.addNode(new Estacion("Constitución de 1917", 555, 682));
        g.addNode(new Estacion("Patriotismo", 156, 513));
        g.addNode(new Estacion("Chilpancingo", 191, 501));
        g.addNode(new Estacion("Lázaro Cárdenas", 262, 502));
        g.addNode(new Estacion("Mixiuhca", 368, 472));
        g.addNode(new Estacion("Velódromo", 403, 470));
        g.addNode(new Estacion("Ciudad Deportiva", 446, 472));
        g.addNode(new Estacion("Puebla", 477, 471));
        g.addNode(new Estacion("Agrícola Oriental", 509, 472));
        g.addNode(new Estacion("Canal de San Juan", 549, 480));
        g.addNode(new Estacion("Tepalcates", 595, 504));
        g.addNode(new Estacion("Guelatao", 623, 532));
        g.addNode(new Estacion("Peñón Viejo", 650, 557));
        g.addNode(new Estacion("Acatitla", 678, 586));
        g.addNode(new Estacion("Santa Marta", 713, 610));
        g.addNode(new Estacion("Los Reyes", 754, 610));
        g.addNode(new Estacion("La Paz", 797, 650));
        g.addNode(new Estacion("Buenavista", 226, 367));
        g.addNode(new Estacion("Lagunilla", 291, 368));
        g.addNode(new Estacion("Tepito", 316, 367));
        g.addNode(new Estacion("Ricardo Flores Magón", 399, 376));
        g.addNode(new Estacion("Romero Rubio", 414, 362));
        g.addNode(new Estacion("Deportivo Oceanía", 450, 326));
        g.addNode(new Estacion("Bosques de Aragón", 484, 292));
        g.addNode(new Estacion("Villa de Aragón", 507, 268));
        g.addNode(new Estacion("Nezahualcóyotl", 534, 240));
        g.addNode(new Estacion("Impulsora", 545, 201));
        g.addNode(new Estacion("Río de los Remedios", 544, 164));
        g.addNode(new Estacion("Múzquiz", 545, 130));
        g.addNode(new Estacion("Ecatepec", 544, 85));
        g.addNode(new Estacion("Olímpica", 544, 62));
        g.addNode(new Estacion("Plaza Aragón", 544, 34));
        g.addNode(new Estacion("Ciudad Azteca", 545, 6));
        g.addNode(new Estacion("Insurgentes Sur", 172, 624));
        g.addNode(new Estacion("Hospital 20 de Noviembre", 199, 624));
        g.addNode(new Estacion("Parque de los Venados", 234, 643));
        g.addNode(new Estacion("Eje Central", 267, 654));
        g.addNode(new Estacion("Mexicaltzingo", 366, 652));
        g.addNode(new Estacion("Culhuacán", 420, 704));
        g.addNode(new Estacion("San Andrés Tomatlán", 420, 732));
        g.addNode(new Estacion("Lomas Estrella", 446, 757));
        g.addNode(new Estacion("Calle 11", 475, 757));
        g.addNode(new Estacion("Periférico Oriente", 513, 757));
        g.addNode(new Estacion("Tezonco", 529, 774));
        g.addNode(new Estacion("Olivos", 561, 772));
        g.addNode(new Estacion("Nopalera", 591, 772));
        g.addNode(new Estacion("Zapotitlán", 623, 773));
        g.addNode(new Estacion("Tlaltenco", 651, 777));
        g.addNode(new Estacion("Tláhuac", 675, 801));

        
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Observatorio"))), g.get(g.indexOf(Estacion.get("Tacubaya"))), 1262, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacubaya"))), g.get(g.indexOf(Estacion.get("Juanacatlán"))), 1158, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacubaya"))), g.get(g.indexOf(Estacion.get("Constituyentes"))), 1005, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacubaya"))), g.get(g.indexOf(Estacion.get("San Pedro de los Pinos"))), 1084, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacubaya"))), g.get(g.indexOf(Estacion.get("Patriotismo"))), 1133, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Juanacatlán"))), g.get(g.indexOf(Estacion.get("Chapultepec"))), 973, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chapultepec"))), g.get(g.indexOf(Estacion.get("Sevilla"))), 501, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Sevilla"))), g.get(g.indexOf(Estacion.get("Insurgentes"))), 645, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Insurgentes"))), g.get(g.indexOf(Estacion.get("Cuauhtémoc"))), 793, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Cuauhtémoc"))), g.get(g.indexOf(Estacion.get("Balderas"))), 409, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Balderas"))), g.get(g.indexOf(Estacion.get("Salto del Agua"))), 458, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Balderas"))), g.get(g.indexOf(Estacion.get("Juárez"))), 659, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Balderas"))), g.get(g.indexOf(Estacion.get("Niños Héroes"))), 665, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Salto del Agua"))), g.get(g.indexOf(Estacion.get("Isabel la Católica"))), 445, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Salto del Agua"))), g.get(g.indexOf(Estacion.get("San Juan de Letrán"))), 292, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Salto del Agua"))), g.get(g.indexOf(Estacion.get("Doctores"))), 564, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Isabel la Católica"))), g.get(g.indexOf(Estacion.get("Pino Suárez"))), 382, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pino Suárez"))), g.get(g.indexOf(Estacion.get("Merced"))), 745, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pino Suárez"))), g.get(g.indexOf(Estacion.get("Zócalo"))), 745, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pino Suárez"))), g.get(g.indexOf(Estacion.get("San Antonio Abad"))), 817, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Merced"))), g.get(g.indexOf(Estacion.get("Candelaria"))), 698, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Candelaria"))), g.get(g.indexOf(Estacion.get("San Lázaro"))), 866, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Candelaria"))), g.get(g.indexOf(Estacion.get("Morelos"))), 1062, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Candelaria"))), g.get(g.indexOf(Estacion.get("Fray Servando"))), 633, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Lázaro"))), g.get(g.indexOf(Estacion.get("Moctezuma"))), 478, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Lázaro"))), g.get(g.indexOf(Estacion.get("Ricardo Flores Magón"))), 907, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Lázaro"))), g.get(g.indexOf(Estacion.get("Morelos"))), 1296, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Moctezuma"))), g.get(g.indexOf(Estacion.get("Balbuena"))), 703, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Balbuena"))), g.get(g.indexOf(Estacion.get("Boulevard Puerto Aéreo"))), 595, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Boulevard Puerto Aéreo"))), g.get(g.indexOf(Estacion.get("Gómez Farías"))), 611, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Gómez Farías"))), g.get(g.indexOf(Estacion.get("Zaragoza"))), 762, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Zaragoza"))), g.get(g.indexOf(Estacion.get("Pantitlán"))), 1320, 1));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pantitlán"))), g.get(g.indexOf(Estacion.get("Hangares"))), 1644, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pantitlán"))), g.get(g.indexOf(Estacion.get("Puebla"))), 1380, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Pantitlán"))), g.get(g.indexOf(Estacion.get("Agrícola Oriental"))), 1409, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Cuatro Caminos"))), g.get(g.indexOf(Estacion.get("Panteones"))), 1639, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Panteones"))), g.get(g.indexOf(Estacion.get("Tacuba"))), 1416, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacuba"))), g.get(g.indexOf(Estacion.get("Cuitláhuac"))), 637, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacuba"))), g.get(g.indexOf(Estacion.get("Refinería"))), 1295, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tacuba"))), g.get(g.indexOf(Estacion.get("San Joaquín"))), 1433, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Cuitláhuac"))), g.get(g.indexOf(Estacion.get("Popotla"))), 620, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Popotla"))), g.get(g.indexOf(Estacion.get("Colegio Militar"))), 462, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Colegio Militar"))), g.get(g.indexOf(Estacion.get("Normal"))), 516, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Normal"))), g.get(g.indexOf(Estacion.get("San Cosme"))), 657, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Cosme"))), g.get(g.indexOf(Estacion.get("Revolución"))), 537, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Revolución"))), g.get(g.indexOf(Estacion.get("Hidalgo"))), 587, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Hidalgo"))), g.get(g.indexOf(Estacion.get("Guerrero"))), 702, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Hidalgo"))), g.get(g.indexOf(Estacion.get("Juárez"))), 251, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Hidalgo"))), g.get(g.indexOf(Estacion.get("Bellas Artes"))), 447, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Bellas Artes"))), g.get(g.indexOf(Estacion.get("Allende"))), 387, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Bellas Artes"))), g.get(g.indexOf(Estacion.get("Garibaldi"))), 634, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Bellas Artes"))), g.get(g.indexOf(Estacion.get("San Juan de Letrán"))), 456, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Allende"))), g.get(g.indexOf(Estacion.get("Zócalo"))), 602, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Antonio Abad"))), g.get(g.indexOf(Estacion.get("Chabacano"))), 642, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chabacano"))), g.get(g.indexOf(Estacion.get("Obrera"))), 1143, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chabacano"))), g.get(g.indexOf(Estacion.get("La Viga"))), 843, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chabacano"))), g.get(g.indexOf(Estacion.get("Jamaica"))), 1031, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chabacano"))), g.get(g.indexOf(Estacion.get("Lázaro Cárdenas"))), 1000, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Chabacano"))), g.get(g.indexOf(Estacion.get("Viaducto"))), 774, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Viaducto"))), g.get(g.indexOf(Estacion.get("Xola"))), 490, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Xola"))), g.get(g.indexOf(Estacion.get("Villa de Cortés"))), 698, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Villa de Cortés"))), g.get(g.indexOf(Estacion.get("Nativitas"))), 750, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Nativitas"))), g.get(g.indexOf(Estacion.get("Portales"))), 924, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Portales"))), g.get(g.indexOf(Estacion.get("Ermita"))), 748, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ermita"))), g.get(g.indexOf(Estacion.get("General Anaya"))), 838, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ermita"))), g.get(g.indexOf(Estacion.get("Eje Central"))), 895, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ermita"))), g.get(g.indexOf(Estacion.get("Mexicaltzingo"))), 1805, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("General Anaya"))), g.get(g.indexOf(Estacion.get("Tasqueña"))), 1330, 2));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Indios Verdes"))), g.get(g.indexOf(Estacion.get("Deportivo 18 de Marzo"))), 1166, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Deportivo 18 de Marzo"))), g.get(g.indexOf(Estacion.get("Lindavista"))), 1075, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Deportivo 18 de Marzo"))), g.get(g.indexOf(Estacion.get("La Villa-Basílica"))), 570, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Deportivo 18 de Marzo"))), g.get(g.indexOf(Estacion.get("Potrero"))), 966, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Potrero"))), g.get(g.indexOf(Estacion.get("La Raza"))), 1106, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("La Raza"))), g.get(g.indexOf(Estacion.get("Tlatelolco"))), 1445, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("La Raza"))), g.get(g.indexOf(Estacion.get("Autobuses del Norte"))), 975, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("La Raza"))), g.get(g.indexOf(Estacion.get("Misterios"))), 892, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tlatelolco"))), g.get(g.indexOf(Estacion.get("Guerrero"))), 1042, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Guerrero"))), g.get(g.indexOf(Estacion.get("Garibaldi"))), 757, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Guerrero"))), g.get(g.indexOf(Estacion.get("Buenavista"))), 521, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Niños Héroes"))), g.get(g.indexOf(Estacion.get("Hospital General"))), 559, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Hospital General"))), g.get(g.indexOf(Estacion.get("Centro Médico"))), 653, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Centro Médico"))), g.get(g.indexOf(Estacion.get("Lázaro Cárdenas"))), 1059, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Centro Médico"))), g.get(g.indexOf(Estacion.get("Chilpancingo"))), 1152, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Centro Médico"))), g.get(g.indexOf(Estacion.get("Etiopía/Plaza de la Transparencia"))), 1119, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Etiopía/Plaza de la Transparencia"))), g.get(g.indexOf(Estacion.get("Eugenia"))), 950, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Eugenia"))), g.get(g.indexOf(Estacion.get("División del Norte"))), 715, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("División del Norte"))), g.get(g.indexOf(Estacion.get("Zapata"))), 794, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Zapata"))), g.get(g.indexOf(Estacion.get("Parque de los Venados"))), 563, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Zapata"))), g.get(g.indexOf(Estacion.get("Hospital 20 de Noviembre"))), 450, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Zapata"))), g.get(g.indexOf(Estacion.get("Coyoacán"))), 1153, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Coyoacán"))), g.get(g.indexOf(Estacion.get("Viveros/Derechos Humanos"))), 908, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Viveros/Derechos Humanos"))), g.get(g.indexOf(Estacion.get("Miguel Ángel de Quevedo"))), 824, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Miguel Ángel de Quevedo"))), g.get(g.indexOf(Estacion.get("Copilco"))), 1295, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Copilco"))), g.get(g.indexOf(Estacion.get("Universidad"))), 1306, 3));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Martín Carrera"))), g.get(g.indexOf(Estacion.get("La Villa-Basílica"))), 1141, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Martín Carrera"))), g.get(g.indexOf(Estacion.get("Talismán"))), 1129, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Talismán"))), g.get(g.indexOf(Estacion.get("Bondojito"))), 959, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Bondojito"))), g.get(g.indexOf(Estacion.get("Consulado"))), 645, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Consulado"))), g.get(g.indexOf(Estacion.get("Canal del Norte"))), 884, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Consulado"))), g.get(g.indexOf(Estacion.get("Valle Gómez"))), 679, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Consulado"))), g.get(g.indexOf(Estacion.get("Eduardo Molina"))), 815, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Canal del Norte"))), g.get(g.indexOf(Estacion.get("Morelos"))), 910, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Morelos"))), g.get(g.indexOf(Estacion.get("Tepito"))), 498, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Fray Servando"))), g.get(g.indexOf(Estacion.get("Jamaica"))), 1033, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Jamaica"))), g.get(g.indexOf(Estacion.get("Santa Anita"))), 758, 4));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Jamaica"))), g.get(g.indexOf(Estacion.get("Mixiuhca"))), 942, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Santa Anita"))), g.get(g.indexOf(Estacion.get("La Viga"))), 633, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Santa Anita"))), g.get(g.indexOf(Estacion.get("Coyuya"))), 968, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Politécnico"))), g.get(g.indexOf(Estacion.get("Instituto del Petróleo"))), 1188, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Instituto del Petróleo"))), g.get(g.indexOf(Estacion.get("Vallejo"))), 755, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Instituto del Petróleo"))), g.get(g.indexOf(Estacion.get("Lindavista"))), 1258, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Instituto del Petróleo"))), g.get(g.indexOf(Estacion.get("Autobuses del Norte"))), 1067, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Misterios"))), g.get(g.indexOf(Estacion.get("Valle Gómez"))), 969, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Eduardo Molina"))), g.get(g.indexOf(Estacion.get("Aragón"))), 860, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Aragón"))), g.get(g.indexOf(Estacion.get("Oceanía"))), 1219, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Oceanía"))), g.get(g.indexOf(Estacion.get("Terminal Aérea"))), 1174, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Oceanía"))), g.get(g.indexOf(Estacion.get("Romero Rubio"))), 809, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Oceanía"))), g.get(g.indexOf(Estacion.get("Deportivo Oceanía"))), 863, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Terminal Aérea"))), g.get(g.indexOf(Estacion.get("Hangares"))), 1153, 5));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("El Rosario"))), g.get(g.indexOf(Estacion.get("Tezozómoc"))), 1257, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("El Rosario"))), g.get(g.indexOf(Estacion.get("Aquiles Serdán"))), 1615, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tezozómoc"))), g.get(g.indexOf(Estacion.get("Azcapotzalco"))), 973, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Azcapotzalco"))), g.get(g.indexOf(Estacion.get("Ferrería"))), 1173, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ferrería"))), g.get(g.indexOf(Estacion.get("Norte 45"))), 1072, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Norte 45"))), g.get(g.indexOf(Estacion.get("Vallejo"))), 660, 6));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Aquiles Serdán"))), g.get(g.indexOf(Estacion.get("Camarones"))), 1402, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Camarones"))), g.get(g.indexOf(Estacion.get("Refinería"))), 952, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Joaquín"))), g.get(g.indexOf(Estacion.get("Polanco"))), 1163, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Polanco"))), g.get(g.indexOf(Estacion.get("Auditorio"))), 812, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Auditorio"))), g.get(g.indexOf(Estacion.get("Constituyentes"))), 1430, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Pedro de los Pinos"))), g.get(g.indexOf(Estacion.get("San Antonio"))), 606, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Antonio"))), g.get(g.indexOf(Estacion.get("Mixcoac"))), 788, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Mixcoac"))), g.get(g.indexOf(Estacion.get("Barranca del Muerto"))), 1476, 7));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Mixcoac"))), g.get(g.indexOf(Estacion.get("Insurgentes Sur"))), 651, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Garibaldi"))), g.get(g.indexOf(Estacion.get("Lagunilla"))), 474, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Doctores"))), g.get(g.indexOf(Estacion.get("Obrera"))), 761, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Coyuya"))), g.get(g.indexOf(Estacion.get("Iztacalco"))), 993, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Iztacalco"))), g.get(g.indexOf(Estacion.get("Apatlaco"))), 910, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Apatlaco"))), g.get(g.indexOf(Estacion.get("Aculco"))), 534, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Aculco"))), g.get(g.indexOf(Estacion.get("Escuadrón 201"))), 789, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Escuadrón 201"))), g.get(g.indexOf(Estacion.get("Atlalilco"))), 1738, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Atlalilco"))), g.get(g.indexOf(Estacion.get("Iztapalapa"))), 732, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Atlalilco"))), g.get(g.indexOf(Estacion.get("Mexicaltzingo"))), 1922, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Atlalilco"))), g.get(g.indexOf(Estacion.get("Culhuacán"))), 1671, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Iztapalapa"))), g.get(g.indexOf(Estacion.get("Cerro de la Estrella"))), 717, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Cerro de la Estrella"))), g.get(g.indexOf(Estacion.get("U.A.M. I"))), 1135, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("U.A.M. I"))), g.get(g.indexOf(Estacion.get("Constitución de 1917"))), 1137, 8));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Patriotismo"))), g.get(g.indexOf(Estacion.get("Chilpancingo"))), 955, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Mixiuhca"))), g.get(g.indexOf(Estacion.get("Velódromo"))), 821, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Velódromo"))), g.get(g.indexOf(Estacion.get("Ciudad Deportiva"))), 1110, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ciudad Deportiva"))), g.get(g.indexOf(Estacion.get("Puebla"))), 800, 9));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Agrícola Oriental"))), g.get(g.indexOf(Estacion.get("Canal de San Juan"))), 1093, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Canal de San Juan"))), g.get(g.indexOf(Estacion.get("Tepalcates"))), 1456, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tepalcates"))), g.get(g.indexOf(Estacion.get("Guelatao"))), 1161, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Guelatao"))), g.get(g.indexOf(Estacion.get("Peñón Viejo"))), 2206, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Peñón Viejo"))), g.get(g.indexOf(Estacion.get("Acatitla"))), 1379, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Acatitla"))), g.get(g.indexOf(Estacion.get("Santa Marta"))), 1100, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Santa Marta"))), g.get(g.indexOf(Estacion.get("Los Reyes"))), 1783, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Los Reyes"))), g.get(g.indexOf(Estacion.get("La Paz"))), 1956, 10));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Lagunilla"))), g.get(g.indexOf(Estacion.get("Tepito"))), 611, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ricardo Flores Magón"))), g.get(g.indexOf(Estacion.get("Romero Rubio"))), 908, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Deportivo Oceanía"))), g.get(g.indexOf(Estacion.get("Bosques de Aragón"))), 1165, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Bosques de Aragón"))), g.get(g.indexOf(Estacion.get("Villa de Aragón"))), 784, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Villa de Aragón"))), g.get(g.indexOf(Estacion.get("Nezahualcóyotl"))), 1335, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Nezahualcóyotl"))), g.get(g.indexOf(Estacion.get("Impulsora"))), 1393, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Impulsora"))), g.get(g.indexOf(Estacion.get("Río de los Remedios"))), 436, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Río de los Remedios"))), g.get(g.indexOf(Estacion.get("Múzquiz"))), 1155, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Múzquiz"))), g.get(g.indexOf(Estacion.get("Ecatepec"))), 1485, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Ecatepec"))), g.get(g.indexOf(Estacion.get("Olímpica"))), 596, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Olímpica"))), g.get(g.indexOf(Estacion.get("Plaza Aragón"))), 709, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Plaza Aragón"))), g.get(g.indexOf(Estacion.get("Ciudad Azteca"))), 574, 11));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Insurgentes Sur"))), g.get(g.indexOf(Estacion.get("Hospital 20 de Noviembre"))), 725, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Parque de los Venados"))), g.get(g.indexOf(Estacion.get("Eje Central"))), 1280, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Culhuacán"))), g.get(g.indexOf(Estacion.get("San Andrés Tomatlán"))), 990, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("San Andrés Tomatlán"))), g.get(g.indexOf(Estacion.get("Lomas Estrella"))), 1060, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Lomas Estrella"))), g.get(g.indexOf(Estacion.get("Calle 11"))), 906, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Calle 11"))), g.get(g.indexOf(Estacion.get("Periférico Oriente"))), 1111, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Periférico Oriente"))), g.get(g.indexOf(Estacion.get("Tezonco"))), 1545, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tezonco"))), g.get(g.indexOf(Estacion.get("Olivos"))), 490, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Olivos"))), g.get(g.indexOf(Estacion.get("Nopalera"))), 1360, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Nopalera"))), g.get(g.indexOf(Estacion.get("Zapotitlán"))), 1276, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Zapotitlán"))), g.get(g.indexOf(Estacion.get("Tlaltenco"))), 1115, 12));
        g.addEdge(new Via(g.get(g.indexOf(Estacion.get("Tlaltenco"))), g.get(g.indexOf(Estacion.get("Tláhuac"))), 1298, 12));

        
        return g;
        
    }
    
}
